spring.application.name=SpringJdbcAssignementThree

spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=truezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
